import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { getYtmCredentials } from './ytm-account.js';
import { db } from './db.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const DATA = join(ROOT, 'data');
/** Cookie header brut (une ligne) — pour youtubei.js */
export const YT_COOKIE_HEADER_PATH = join(DATA, 'youtube-cookies.header');
/** Netscape cookies.txt — pour yt-dlp --cookies (obligatoire : plus de --add-header Cookie) */
export const YT_COOKIE_NETSCAPE_PATH = join(DATA, 'youtube-cookies.txt');

mkdirSync(DATA, { recursive: true });

export type YoutubeCookiesStatus = {
  configured: boolean;
  source: 'env' | 'header-file' | 'netscape-file' | 'ytm-account' | null;
  headerPath: string;
  netscapePath: string;
  hint: string;
};

function looksLikeNetscape(raw: string) {
  return /^# Netscape/i.test(raw) || /\tyoutube\.com\t/.test(raw);
}

/** Convertit `a=1; b=2` → fichier Netscape (domaine .youtube.com). */
export function cookieHeaderToNetscape(cookieHeader: string): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by PLM — do not edit by hand',
    '',
  ];
  const seen = new Set<string>();
  for (const part of String(cookieHeader || '').split(';')) {
    const idx = part.indexOf('=');
    if (idx <= 0) continue;
    const name = part.slice(0, idx).trim();
    const value = part.slice(idx + 1).trim();
    if (!name || seen.has(name)) continue;
    seen.add(name);
    // domain, includeSubdomains, path, secure, expires, name, value
    lines.push(`.youtube.com\tTRUE\t/\tTRUE\t2147483647\t${name}\t${value}`);
  }
  return `${lines.join('\n')}\n`;
}

/** Netscape → header Cookie= (pour Innertube). */
export function netscapeToCookieHeader(raw: string): string {
  const map = new Map<string, string>();
  for (const line of String(raw || '').split(/\r?\n/)) {
    if (!line || line.startsWith('#')) continue;
    const cols = line.split('\t');
    if (cols.length < 7) continue;
    const domain = cols[0] || '';
    if (!/youtube\.com|google\.com/i.test(domain)) continue;
    const name = cols[5];
    const value = cols[6];
    if (name) map.set(name, `${name}=${value}`);
  }
  return [...map.values()].join('; ');
}

function cookieFromYtmAccounts(): string | undefined {
  try {
    const row = db
      .prepare(
        `SELECT user_id FROM ytm_accounts WHERE cookie_enc IS NOT NULL AND cookie_enc != '' LIMIT 1`,
      )
      .get() as { user_id: string } | undefined;
    if (!row?.user_id) return undefined;
    const creds = getYtmCredentials(row.user_id);
    const c = creds?.cookie?.trim();
    return c ? c.replace(/^Cookie:\s*/i, '') : undefined;
  } catch {
    return undefined;
  }
}

function ensureNetscapeFromHeader(header: string) {
  try {
    writeFileSync(YT_COOKIE_NETSCAPE_PATH, cookieHeaderToNetscape(header), 'utf8');
  } catch {
    /* ignore */
  }
}

/** Cookie header pour Innertube (youtubei.js). */
export function resolveYoutubeCookieHeader(): string | undefined {
  const env = (process.env.YOUTUBE_COOKIES || '').trim();
  if (env) {
    const h = env.replace(/^Cookie:\s*/i, '');
    ensureNetscapeFromHeader(h);
    return h;
  }

  const fileEnv = (process.env.YOUTUBE_COOKIES_FILE || '').trim();
  if (fileEnv && existsSync(fileEnv)) {
    const raw = readFileSync(fileEnv, 'utf8').trim();
    if (raw && looksLikeNetscape(raw)) {
      const h = netscapeToCookieHeader(raw);
      if (h) return h;
    }
    if (raw) return raw.replace(/^Cookie:\s*/i, '');
  }

  if (existsSync(YT_COOKIE_HEADER_PATH)) {
    const raw = readFileSync(YT_COOKIE_HEADER_PATH, 'utf8').trim();
    if (raw) {
      ensureNetscapeFromHeader(raw);
      return raw.replace(/^Cookie:\s*/i, '');
    }
  }

  if (existsSync(YT_COOKIE_NETSCAPE_PATH)) {
    try {
      const raw = readFileSync(YT_COOKIE_NETSCAPE_PATH, 'utf8');
      if (looksLikeNetscape(raw)) {
        const h = netscapeToCookieHeader(raw);
        if (h) return h;
      }
    } catch {
      /* ignore */
    }
  }

  return cookieFromYtmAccounts();
}

/** Chemin cookies Netscape pour yt-dlp, ou undefined. */
export function resolveYoutubeCookiesFileForYtDlp(): string | undefined {
  const fileEnv = (process.env.YOUTUBE_COOKIES_FILE || '').trim();
  if (fileEnv && existsSync(fileEnv)) {
    try {
      if (looksLikeNetscape(readFileSync(fileEnv, 'utf8'))) return fileEnv;
    } catch {
      /* ignore */
    }
  }
  // Toujours régénérer depuis le header si présent (évite fichier périmé / absent)
  const header = (() => {
    try {
      if (existsSync(YT_COOKIE_HEADER_PATH)) {
        return readFileSync(YT_COOKIE_HEADER_PATH, 'utf8').trim();
      }
    } catch {
      /* ignore */
    }
    return '';
  })();
  if (header) {
    ensureNetscapeFromHeader(header);
    return YT_COOKIE_NETSCAPE_PATH;
  }
  if (existsSync(YT_COOKIE_NETSCAPE_PATH)) {
    try {
      if (looksLikeNetscape(readFileSync(YT_COOKIE_NETSCAPE_PATH, 'utf8'))) {
        return YT_COOKIE_NETSCAPE_PATH;
      }
    } catch {
      /* ignore */
    }
  }
  return undefined;
}

/**
 * Args cookies pour yt-dlp.
 * Fichier Netscape uniquement par défaut.
 * `--cookies-from-browser` est opt-in (`YTDLP_COOKIES_FROM_BROWSER=1`) :
 * en local Chrome ouvert / cookies partiels → souvent « Requested format is not available ».
 *
 * Les cookies ne sont **jamais obligatoires** (pas de compte Premium requis).
 * Ils restent un boost anti-bot optionnel.
 */
export function ytDlpCookieArgs(): string[] {
  const file = resolveYoutubeCookiesFileForYtDlp();
  if (file) return ['--cookies', file];
  if (process.env.YTDLP_COOKIES_FROM_BROWSER === '1') {
    const browser = (process.env.YTDLP_BROWSER || 'chrome').trim() || 'chrome';
    return ['--cookies-from-browser', browser];
  }
  return [];
}

/**
 * Ordre d’essai yt-dlp : **anonyme d’abord**, cookies ensuite (optionnel).
 * Évite de dépendre d’une session Premium / cookies périmés qui cassent les formats.
 * Override : `YTDLP_COOKIES_FIRST=1` pour l’ancien ordre (cookies → anon).
 */
export function ytDlpCookieArgSets(): string[][] {
  const withCookies = ytDlpCookieArgs();
  if (!withCookies.length) return [[]];
  if (process.env.YTDLP_COOKIES_FIRST === '1') {
    return [withCookies, []];
  }
  return [[], withCookies];
}

/** Sélecteurs audio yt-dlp — **m4a (140) d’abord** pour Exo/Media3 (webm/opus plus fragile). */
export const YTDLP_AUDIO_FORMAT_CANDIDATES = [
  '140/139/bestaudio[ext=m4a]/bestaudio[acodec*=mp4a]',
  '251/250/249/bestaudio[ext=webm]/bestaudio',
  '140/251/250/249/139/bestaudio[acodec!=none]/bestaudio',
] as const;

export function youtubeCookiesFingerprint(): string {
  const h = resolveYoutubeCookieHeader() || '';
  const f = resolveYoutubeCookiesFileForYtDlp() || '';
  return createHash('sha256').update(h + '|' + f).digest('hex').slice(0, 16);
}

export function youtubeCookiesStatus(): YoutubeCookiesStatus {
  const header = resolveYoutubeCookieHeader();
  const netscape = resolveYoutubeCookiesFileForYtDlp();
  const appEnv = String(process.env.APP_ENV || 'local').toLowerCase();
  let source: YoutubeCookiesStatus['source'] = null;
  if ((process.env.YOUTUBE_COOKIES || '').trim()) source = 'env';
  else if (existsSync(YT_COOKIE_HEADER_PATH) && readFileSync(YT_COOKIE_HEADER_PATH, 'utf8').trim())
    source = 'header-file';
  else if (netscape) source = 'netscape-file';
  else if (header) source = 'ytm-account';

  return {
    configured: Boolean(header || netscape),
    source,
    headerPath: YT_COOKIE_HEADER_PATH,
    netscapePath: YT_COOKIE_NETSCAPE_PATH,
    hint: header || netscape
      ? 'Session navigateur optionnelle (anti-bot). Pas de Premium requis — stream OK aussi sans cookies.'
      : appEnv === 'local' || appEnv === 'development'
        ? 'Aucun cookie YouTube — normal. Stream via yt-dlp/Innertube sans Premium.'
        : 'Aucun cookie — OK. Préfère STREAM_UPSTREAM (PC maison) ; cookies navigateur optionnels, jamais Premium.',
  };
}

/** Sauvegarde un header Cookie=… ou un fichier Netscape. */
export function saveYoutubeCookieHeader(raw: string) {
  let text = String(raw || '').trim();
  if (looksLikeNetscape(text)) {
    const header = netscapeToCookieHeader(text);
    if (header.length < 40) {
      throw new Error('Fichier Netscape sans cookies utiles');
    }
    writeFileSync(YT_COOKIE_NETSCAPE_PATH, text.endsWith('\n') ? text : `${text}\n`, 'utf8');
    writeFileSync(YT_COOKIE_HEADER_PATH, `${header}\n`, 'utf8');
    return youtubeCookiesStatus();
  }

  const cleaned = text.replace(/^Cookie:\s*/i, '');
  if (cleaned.length < 40) {
    throw new Error('Cookie trop court — utilise bash scripts/push-youtube-cookies.sh');
  }
  writeFileSync(YT_COOKIE_HEADER_PATH, `${cleaned}\n`, 'utf8');
  writeFileSync(YT_COOKIE_NETSCAPE_PATH, cookieHeaderToNetscape(cleaned), 'utf8');
  return youtubeCookiesStatus();
}

export function clearYoutubeCookieHeader() {
  writeFileSync(YT_COOKIE_HEADER_PATH, '', 'utf8');
  try {
    if (existsSync(YT_COOKIE_NETSCAPE_PATH)) unlinkSync(YT_COOKIE_NETSCAPE_PATH);
  } catch {
    writeFileSync(YT_COOKIE_NETSCAPE_PATH, '', 'utf8');
  }
  return youtubeCookiesStatus();
}
